services:

  ahadiiq-postgres:
    image: postgres:17
    restart: unless-stopped
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Africa/Nairobi"

    volumes:
      - ahadiiq_postgres_data:/var/lib/postgresql/data
    
    # HC to ensure DB is ready before other services start. it will retry 5 times with intervals of 10 seconds. A test script is used to check if DB is ready with pg_isready.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s


  ahadiiq-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
  ahadiiq_postgres_data: