"""add extracted_texts table

Revision ID: 5fbe01d85823
Revises: bd89a1da8953
Create Date: 2026-08-31 15:52:17.208396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbe01d85823'
down_revision: Union[str, Sequence[str], None] = 'bd89a1da8953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_texts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_texts')
    # ### end Alembic commands ###
