"""make obligation clause_id nullable

Revision ID: a9db47829268
Revises: 5f645d2748d9
Create Date: 2026-10-09 15:10:08.026798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9db47829268'
down_revision: Union[str, Sequence[str], None] = '5f645d2748d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('obligations', 'clause_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('obligations', 'clause_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
