"""add clauses table and JSONB columns to agreements

Revision ID: c68c958ab61b
Revises: 5fbe01d85823
Create Date: 2026-09-07 14:53:59.834760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c68c958ab61b'
down_revision: Union[str, Sequence[str], None] = '5fbe01d85823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agreement_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('clause_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notice_period', sa.Integer(), nullable=True),
    sa.Column('relative_to', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agreements', sa.Column('parties', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agreements', sa.Column('signatories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'signatories')
    op.drop_column('agreements', 'parties')
    op.drop_table('clauses')
    # ### end Alembic commands ###
