"""add effective_date and expiry_date to agreements

Revision ID: c8aebf49a267
Revises: c68c958ab61b
Create Date: 2026-09-15 14:48:32.101136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8aebf49a267'
down_revision: Union[str, Sequence[str], None] = 'c68c958ab61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreements', sa.Column('effective_date', sa.Date(), nullable=True))
    op.add_column('agreements', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreements', 'expiry_date')
    op.drop_column('agreements', 'effective_date')
    # ### end Alembic commands ###
